### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by narimiran**
Some minor things I've noticed while exploring the repo.

### CODE REVIEW

**Review by jakubgs — COMMENTED** [review]
Please don't change `ansible/terraform.py` and `ansible/versioncheck.py`, as those exist in other repos and discrepancies across different fleet repos will make mass updates harder.

**Comment by jakubgs** [comment]
You can fix those typos here instead: https://github.com/status-im/infra-template

**Comment by narimiran** [comment]
> Please don't change ansible/terraform.py and ansible/versioncheck.py, as those exist in other repos and discrepancies across different fleet repos will make mass updates harder.

Ok, I didn't know that.

The changes in those files are now reverted.

**Review by jakubgs — APPROVED** [review]
Second commit message is not accurate since you do change `ansible/roles/nimbus-stats/files/collect.py`.

**Pull request merged**
