### PR TITLE
nimbus.prater: reduce layout to just 2 hosts

### PR DESCRIPTION
**Pull request by jakubgs**
This testnet will be dead within ~3 weeks.

### CODE REVIEW

**Comment by jakubgs** [comment]
Created a ticket to reinstall no longer used Prater hosts: https://client.innovahosting.net/viewticket.php?tid=999870&c=sfx4KSsm

We can use them for Jenkins and GitHub CI and other uses for now.

**Comment by arnetheduck** [comment]
is any of these removed nodes a bootnode? if yes, it needs to keep going.. https://github.com/eth-clients/goerli/blob/main/prater/bootstrap_nodes.txt

**Comment by jakubgs** [comment]
Whooooops, I forgot those were a thing. Those were the two AWS nodes:
```
stable-large-01.aws-eu-central-1a.nimbus.prater.statusim.net
-testing-large-01.aws-eu-central-1a.nimbus.prater.statusim.net
```
Looks like I will have to re-create those.

**Comment by jakubgs** [comment]
Yeaaaaah, I think we can't recover the IPs for those bootstrap nodes. So we can't recover them. Sorry @arnetheduck .

**Comment by arnetheduck** [comment]
ok, how can we avoid that in the future? ie these nodes should ideally have some reasonably identifiable property _somewhere_ - the same applies to mainnet etc, any transition needs to be managed

**Review by tersec — APPROVED** [review]

**Comment by jakubgs** [comment]
Well, best way to identify them is I guess to just use the word `boot` in the hostname, so it's clear which one is a bootstrap one.

Other than that maybe comments in layouts files and bootstrap section in `README`.

**Comment by arnetheduck** [comment]
+1 hostname

**Pull request merged**
