### PR TITLE
Add hetzner dedicated server

### PR DESCRIPTION
**Pull request by arthurk**
This PR adds the hetzner dedicated server mentioned in #52 to the infra.

The server will run stable branch on mainnet.

The builds are set up and work:
https://hub.docker.com/layers/statusteam/nimbus_beacon_node/stable-metal-01/images/sha256-3f38ccf62e519cf4beaeda5c82bcd6bb9887aea325221b6c8da6580632d0ade9?context=explore

However, the problem is that the server is not added to the ansible inventory under `[nimbus.mainnet]`,
which prevents the `infra-role-beacon-node` role to run. I'm looking more into
it.

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
The `hetzner` dummy role is missing one group that `infra-tf-amazon-web-services` has:
https://github.com/status-im/infra-tf-amazon-web-services/blob/ee4602f7b3d44b6e56c167bcbd0aeb5e7c8cfe3b/main.tf#L6-L7

**Comment by arnetheduck** [comment]
ideally the mainnet node will be started with `--subscribe-all-subnets` which is better for load testing as well as the health of eth2 in general (at the expense of cpu)

**Comment by jakubgs** [comment]
That's easy, we can just add `beacon_node_subscribe_all: true`. @arthurk

**Review by jakubgs — APPROVED** [review]
Please squash this stuff, it goes together.

**Pull request merged**
